server:
  port: 8008
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
    show-sql: false

  liquibase:
    change-log: classpath:community/db/changelog/db.changelog.yml
    enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
  messages:
    basename: community/messages/common-messages, community/messages/leave-messages, community/messages/people-messages, community/messages/time-messages, community/messages/okr-messages

file:
  storage:
    folders:
      - organization-logos
      - user-image
      - leave-attachments
    base: storage
    encryption-key: ${FILE_ENCRYPT_KEY}

logging:
  level:
    ROOT: WARN

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

jwt:
  access-token:
    signing-key: ${SIGN_IN_KEY}
    expiration-time: 3600000 # Expiration time in milliseconds (1 hour)
  refresh-token:
    long-duration:
      expiration-time: 2592000000 # Expiration time in milliseconds (30 days)
    short-duration:
      expiration-time: 21600000 # Expiration time in milliseconds (6 hours)

encryptDecryptAlgorithm:
  secret: ${ENCRYPT_DECRYPT_SECRET}
